version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    depends_on:
      - redis
  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    depends_on:
      - redis
  redis:
    image: redis:alpine